# Generated by Django 3.2.24 on 2024-03-04 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0002_auto_20240304_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="useremail",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
