# Generated by Django 3.2.24 on 2024-03-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_auto_20240315_1337"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="marital_status",
        ),
    ]
