# Generated by Django 3.2.4 on 2024-03-19 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptors', '0002_alter_adoptor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_adoptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
