# Generated by Django 3.2.24 on 2024-03-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20240306_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='name',
            new_name='dog_name',
        ),
    ]
